/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as metaNodeSol from './MetaNode.sol/index.js';
export type { metaNodeSol };
export type { MetaNodeStake } from './MetaNodeStake.js';
export type { MetaNodeStakeV2 } from './MetaNodeStakeV2.js';